version: 2

# Update configuration for Go modules (gomod)
updates:
  - package-ecosystem: "gomod"  # Specify Go modules as the ecosystem to track
    directory: "/"  # The directory where the go.mod file is located (root in this case)
    schedule:
      interval: "daily"  # Check for updates to Go dependencies daily

  # Update configuration for npm (Node.js) packages
  - package-ecosystem: "npm"  # Specify npm as the ecosystem to track
    directory: "/"  # The directory where the package.json file is located (root in this case)
    schedule:
      interval: "daily"  # Check for updates to npm dependencies daily