name: Year-End Workflow  # This is the name of the workflow, which will appear in the Actions tab.

# Define when this workflow should run using the cron syntax
on:
  schedule:
    - cron: '59 23 31 12 *'  # This schedules the workflow to run at 11:59 PM on December 31st every year.

jobs:
  silvester_task:  # This is the name of the job. You can have multiple jobs in a workflow.
    runs-on: ubuntu-latest  # This specifies that the job will run on the latest available version of Ubuntu.

    steps:
    - name: Checkout repository  # This step checks out the code from the repository.
      uses: actions/checkout@v3  # Uses the checkout action to clone the repository to the runner.
      
    - name: Perform end-of-year tasks  # This step runs the commands to perform the year-end task.
      run: |
        current_year=$(date +'%Y')  # Get the current year (e.g., 2024).
        new_year=$((current_year + 1))  # Calculate the next year (e.g., 2025).
        
        # Search for all files in the repository and replace occurrences of the current year with the new year.
        # The `-i` flag modifies the files in-place.
        find . -type f -exec sed -i "s/$current_year/$new_year/g" {} +  # This replaces the year in all files.
        
    - name: Commit changes  # This step configures Git and commits the changes made in the previous step.
      run: |
        git config --global user.name "github-actions[bot]"  # Set the Git username for the bot user.
        git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Set the Git email for the bot.
        
        git add .  # Stage all the changes made (e.g., replacing the year in the files).

        git commit -m "Happy New Year 🎉"  # Commit the changes with a message.
        
        git push origin HEAD  # Push the commit to the repository's current branch.